/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni/jni.h"
/* Header for class com_diffbot_fasttext_FastTextModel */

#ifndef _Included_com_diffbot_fasttext_FastTextModel
#define _Included_com_diffbot_fasttext_FastTextModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_diffbot_fasttext_FastTextModel
 * Method:    load
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_diffbot_fasttext_FastTextModel_load
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_diffbot_fasttext_FastTextModel
 * Method:    predictProba
 * Signature: (Ljava/lang/String;)Lcom/diffbot/fasttext/Prediction;
 */
JNIEXPORT jobject JNICALL Java_com_diffbot_fasttext_FastTextModel_predictProba
  (JNIEnv *, jobject, jstring);

  /*
   * Class:     com_diffbot_fasttext_FastTextModel
   * Method:    predictProbaTopK
   * Signature: (Ljava/lang/String;I)[Lcom/diffbot/fasttext/Prediction;
   */
  JNIEXPORT jobjectArray JNICALL Java_com_diffbot_fasttext_FastTextModel_predictProbaTopK
    (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_diffbot_fasttext_FastTextModel
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_diffbot_fasttext_FastTextModel_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
