name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-linux:

    runs-on: ubuntu-latest
    container: gcc:10-buster

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Make
        run: |
          cd src/main/native
          pwd
          make